
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.ProfilesEditor.AddItem(FhirKhit.Tools.CodeBlockNested,System.String,System.String,System.String,System.String,Hl7.Fhir.Model.Markdown)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.ElementDefinitionExtensions2.Card(Hl7.Fhir.Model.ElementDefinition,System.Int32,System.Int32)~Hl7.Fhir.Model.ElementDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.ElementDefinitionExtensions2.Card(Hl7.Fhir.Model.ElementDefinition,System.Int32,System.String)~Hl7.Fhir.Model.ElementDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.ElementDefinitionExtensions2.Definition(Hl7.Fhir.Model.ElementDefinition,System.String)~Hl7.Fhir.Model.ElementDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.ElementDefinitionExtensions2.Fixed(Hl7.Fhir.Model.ElementDefinition,Hl7.Fhir.Model.Element)~Hl7.Fhir.Model.ElementDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.ElementDefinitionExtensions2.Pattern(Hl7.Fhir.Model.ElementDefinition,Hl7.Fhir.Model.Element)~Hl7.Fhir.Model.ElementDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.ElementDefinitionExtensions2.Short(Hl7.Fhir.Model.ElementDefinition,System.String)~Hl7.Fhir.Model.ElementDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.ElementDefinitionExtensions2.Type(Hl7.Fhir.Model.ElementDefinition,Hl7.Fhir.Model.ElementDefinition.TypeRefComponent[])~Hl7.Fhir.Model.ElementDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.SDefEditor.Find(System.String)~FhirKhit.Tools.R4.SDefEditor.ElementIndex")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Abstract(Hl7.Fhir.Model.StructureDefinition,System.Nullable{System.Boolean})~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.ContactUrl(Hl7.Fhir.Model.StructureDefinition,System.String)~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Context(Hl7.Fhir.Model.StructureDefinition,Hl7.Fhir.Model.StructureDefinition.ExtensionContextType,System.String)~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Date(Hl7.Fhir.Model.StructureDefinition,Hl7.Fhir.Model.FhirDateTime)~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Derivation(Hl7.Fhir.Model.StructureDefinition,System.Nullable{Hl7.Fhir.Model.StructureDefinition.TypeDerivationRule})~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Description(Hl7.Fhir.Model.StructureDefinition,System.String)~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Kind(Hl7.Fhir.Model.StructureDefinition,System.Nullable{Hl7.Fhir.Model.StructureDefinition.StructureDefinitionKind})~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Name(Hl7.Fhir.Model.StructureDefinition,System.String)~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Publisher(Hl7.Fhir.Model.StructureDefinition,System.String)~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Status(Hl7.Fhir.Model.StructureDefinition,System.Nullable{Hl7.Fhir.Model.PublicationStatus})~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Title(Hl7.Fhir.Model.StructureDefinition,System.String)~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Type(Hl7.Fhir.Model.StructureDefinition,System.String)~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Url(Hl7.Fhir.Model.StructureDefinition,System.String)~Hl7.Fhir.Model.StructureDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:FhirKhit.Tools.R4.StructureDefinitionExtensions2.Version(Hl7.Fhir.Model.StructureDefinition,System.String)~Hl7.Fhir.Model.StructureDefinition")]
